/* granting access */
CREATE DATABASE XX_APP_DBNAME IF NOT EXISTS;
CREATE USER IF NOT EXISTS 'XX_APP_USERNAME'@'%' IDENTIFIED BY 'XX_APP_PASSWORD';
GRANT ALL PRIVILEGES ON XX_APP_DBNAME.* TO 'XX_APP_USERNAME'@'%';

USE XX_APP_DBNAME;

/* some test shit 
CREATE TABLE IF NOT EXISTS KV(
	k VARCHAR(16) NOT NULL PRIMARY KEY,
	v VARCHAR(16) DEFAULT NULL
);
INSERT INTO KV VALUES('mZG{U1xhyTS,_yW0','fuck you');
*/
