# DIPSHIT
management:
  endpoints:
    web:
      exposure:
        include: none
    enabled-by-default: false

spring:

  # JPA
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
    hibernate:
      ddl-auto: never
  sql:
    init:
      mode: never
