instance:
  current_profile: DEV
server:
  port: 8761
  waitTimeInMsWhenSyncEmpty: 5

client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka