instance:
  current_profile: PROD
server:
  port: 8761
  waitTimeInMsWhenSyncEmpty: 1

client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
