instance:
  current_profile: DEV
server:
  port: 8081
spring:
  devtools:
    restart:
      enabled: true

  # DATA SOURCE
  datasource:
    url: jdbc:mariadb://localhost:3306/XX_APP_USERNAME
    driver-class-name: org.mariadb.jdbc.Driver
    password: XX_APP_USERNAME
    username: XX_APP_USERNAME
    validationQuery: SELECT 1
    testWhileIdle: true

# EUREKA
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
