FROM openjdk:17-jdk-alpine
LABEL org.opencontainers.image.authors="mindyourown@fuckingbusiness.com"
COPY target/employment-0.0.1-SNAPSHOT.jar app-0.0.1.jar
ENTRYPOINT ["java","-jar","/app-0.0.1.jar"]
